{{- include "trigger-dev.validateValues" . -}}
{{- include "trigger-dev.generateSecrets" . -}}
{{- if .Values.worker.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "trigger-dev.worker.name" . }}
  namespace: {{ .Values.namespace | default .Release.Namespace }}
  labels:
    {{- include "trigger-dev.labels" . | nindent 4 }}
    app.kubernetes.io/component: worker
spec:
  replicas: {{ .Values.worker.replicas }}
  selector:
    matchLabels:
      {{- include "trigger-dev.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: worker
  template:
    metadata:
      {{- with .Values.worker.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "trigger-dev.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: worker
        {{- with .Values.worker.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "trigger-dev.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      {{- if .Values.worker.initContainers }}
      initContainers:
        {{- toYaml .Values.worker.initContainers | nindent 8 }}
      {{- end }}
      {{- if .Values.priorityClassName }}
      priorityClassName: {{ .Values.priorityClassName }}
      {{- end }}
      {{- with .Values.topologySpreadConstraints }}
      topologySpreadConstraints:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}-worker
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: {{ include "trigger-dev.worker.image" . | quote }}
          imagePullPolicy: {{ .Values.worker.image.pullPolicy }}
          env:
            - name: NODE_ENV
              value: {{ .Values.worker.nodeEnv | quote }}
            - name: HTTP_SERVER_DISABLED
              value: "true"
            - name: WORKER_ENABLED
              value: "true"
            - name: PORT
              value: {{ .Values.worker.service.port | quote }}
            - name: TRIGGER_API_URL
              value: "http://{{ include "trigger-dev.app.name" . }}:{{ .Values.app.service.port }}"
            {{- with .Values.worker.env }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          ports:
            - name: http
              containerPort: {{ .Values.worker.service.port }}
              protocol: TCP
          resources:
            {{- toYaml .Values.resources.worker | nindent 12 }}
          {{- with .Values.worker.nodeSelector }}
          nodeSelector:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.worker.affinity }}
          affinity:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.worker.tolerations }}
          tolerations:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          startupProbe:
            {{- toYaml .Values.worker.startupProbe | nindent 12 }}
          livenessProbe:
            {{- toYaml .Values.worker.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.worker.readinessProbe | nindent 12 }}
{{- end }}