{{- include "trigger-dev.validateValues" . -}}
{{- if .Values.worker.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "trigger-dev.worker.name" . }}
  namespace: {{ .Values.namespace | default .Release.Namespace }}
  labels:
    {{- include "trigger-dev.labels" . | nindent 4 }}
    app.kubernetes.io/component: worker
  {{- with .Values.worker.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.worker.service.type }}
  type: {{ .Values.worker.service.type }}
  {{- end }}
  ports:
    - port: {{ .Values.worker.service.port | default 3000 }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "trigger-dev.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: worker
{{- end }}