{{- include "trigger-dev.validateValues" . -}}
{{- include "trigger-dev.generateSecrets" . -}}
{{- if .Values.worker.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "trigger-dev.worker.name" . }}
  namespace: {{ .Values.namespace | default .Release.Namespace }}
  labels:
    {{- include "trigger-dev.labels" . | nindent 4 }}
    app.kubernetes.io/component: worker
spec:
  replicas: {{ .Values.worker.replicas }}
  selector:
    matchLabels:
      {{- include "trigger-dev.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: worker
  template:
    metadata:
      {{- with .Values.worker.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "trigger-dev.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: worker
        {{- with .Values.worker.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "trigger-dev.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      {{- if .Values.worker.initContainers }}
      initContainers:
        {{- toYaml .Values.worker.initContainers | nindent 8 }}
      {{- end }}
      {{- if .Values.priorityClassName }}
      priorityClassName: {{ .Values.priorityClassName }}
      {{- end }}
      {{- with .Values.topologySpreadConstraints }}
      topologySpreadConstraints:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}-worker
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: {{ include "trigger-dev.worker.image" . | quote }}
          imagePullPolicy: {{ .Values.worker.image.pullPolicy }}
          env:
            - name: NODE_ENV
              value: {{ .Values.worker.nodeEnv | quote }}
            - name: HTTP_SERVER_DISABLED
              value: "true"
            - name: WORKER_ENABLED
              value: "true"
            - name: TRIGGER_API_URL
              value: "http://{{ include "trigger-dev.app.name" . }}:{{ .Values.service.port }}"
            - name: KUBERNETES_FORCE_ENABLED
              value: "true"
            - name: KUBERNETES_NAMESPACE
              value: "{{ .Values.namespace | default .Release.Namespace }}"
            - name: KUBERNETES_IMAGE_PULL_POLICY
              value: "IfNotPresent"
            - name: DATABASE_CONNECTION_RETRIES
              value: "5"
            - name: DATABASE_CONNECTION_RETRY_DELAY_MS
              value: "2000"
            - name: REDIS_CONNECTION_RETRIES
              value: "5"
            - name: REDIS_CONNECTION_RETRY_DELAY_MS
              value: "2000"
            - name: HEALTH_CHECK_INTERVAL_MS
              value: "10000"
            - name: HEALTH_CHECK_TIMEOUT_MS
              value: "5000"
          {{- include "trigger-dev.commonEnv" . | nindent 12 }}
          {{- with .Values.worker.env }}
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.worker.startupProbe }}
          startupProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.worker.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.worker.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          resources:
            {{- toYaml .Values.resources.worker | nindent 12 }}
      {{- with .Values.worker.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.worker.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.worker.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- if .Values.worker.service.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "trigger-dev.worker.name" . }}
  namespace: {{ .Values.namespace | default .Release.Namespace }}
  labels:
    {{- include "trigger-dev.labels" . | nindent 4 }}
    app.kubernetes.io/component: worker
  {{- with .Values.worker.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.worker.service.type }}
  ports:
    - port: {{ .Values.worker.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "trigger-dev.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: worker
{{- end }}
{{- end }}