{{- if .Values.quickstart.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "trigger-dev.fullname" . }}-secrets
  namespace: {{ .Values.namespace | default .Release.Namespace }}
  labels:
    {{- include "trigger-dev.labels" . | nindent 4 }}
type: Opaque
data:
  MAGIC_LINK_SECRET: {{ .Values.secrets.magicLinkSecret | b64enc }}
  ENCRYPTION_KEY: {{ .Values.secrets.encryptionKey | b64enc }}
  TRIGGER_WORKER_TOKEN: {{ .Values.secrets.workerToken | b64enc }}
  MANAGED_WORKER_SECRET: {{ .Values.secrets.managedWorkerSecret | b64enc }}
{{- end }} 