{{/*
This is a stateless deployment that relies on external services:
- Database: External PostgreSQL (e.g., Neon.tech) configured via connection string
- Redis: External Redis instance configured via connection string
- Storage: All file storage is handled by external services
*/}}
{{- if .Values.app.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "trigger-dev.app.name" . }}
  namespace: {{ .Values.namespace | default .Release.Namespace }}
  labels: {{- include "trigger-dev.labels" . | nindent 4 }}
    app.kubernetes.io/component: app
spec:
  replicas: {{ .Values.app.replicas }}
  selector:
    matchLabels: {{- include "trigger-dev.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: app
  template:
    metadata:
      {{- with .Values.app.podAnnotations }}
      annotations: {{- toYaml . | nindent 8 }}
      {{- end }}
      labels: {{- include "trigger-dev.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: app
        {{- with .Values.app.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets: {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "trigger-dev.serviceAccountName" . }}
      securityContext: {{- toYaml .Values.podSecurityContext | nindent 8 }}
      {{- if .Values.app.initContainers }}
      initContainers: {{- toYaml .Values.app.initContainers | nindent 8 }}
      {{- end }}
      {{- if .Values.priorityClassName }}
      priorityClassName: {{ .Values.priorityClassName }}
      {{- end }}
      {{- with .Values.topologySpreadConstraints }}
      topologySpreadConstraints: {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
      - name: {{ .Chart.Name }}-app
        securityContext: {{- toYaml .Values.securityContext | nindent 10 }}
        image: {{ include "trigger-dev.app.image" . | quote }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        envFrom:
        - configMapRef:
            name: {{ include "trigger-dev.app.name" . }}-config
        env:
        - name: TRIGGER_API_URL
          value: "http://{{ include "trigger-dev.app.name" . }}:{{ .Values.service.port }}"
        {{- include "trigger-dev.commonEnv" . | nindent 8 }}
        {{- with .Values.app.env }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        ports:
        - name: http
          containerPort: {{ .Values.service.port }}
          protocol: TCP
        {{- with .Values.app.startupProbe }}
        startupProbe: {{- toYaml . | nindent 10 }}
        {{- end }}
        {{- with .Values.app.livenessProbe }}
        livenessProbe: {{- toYaml . | nindent 10 }}
        {{- end }}
        {{- with .Values.app.readinessProbe }}
        readinessProbe: {{- toYaml . | nindent 10 }}
        {{- end }}
        resources: {{- toYaml .Values.resources.app | nindent 10 }}
      {{- with .Values.app.nodeSelector }}
      nodeSelector: {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.app.affinity }}
      affinity: {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.app.tolerations }}
      tolerations: {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }} 