{{- if .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "trigger-dev.fullname" . }}-role
  namespace: {{ .Values.namespace | default .Release.Namespace }}
  labels:
    {{- include "trigger-dev.labels" . | nindent 4 }}
  annotations:
    # This Role grants permissions for the Trigger.dev supervisor component to manage task pods
    "helm.sh/hook-weight": "-10"
    "trigger.dev/description": "Provides permissions for Trigger.dev to create and manage task runner pods"
rules:
  {{- toYaml .Values.rbac.rules | nindent 2 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "trigger-dev.fullname" . }}-rolebinding
  namespace: {{ .Values.namespace | default .Release.Namespace }}
  labels:
    {{- include "trigger-dev.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook-weight": "-9"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "trigger-dev.fullname" . }}-role
subjects:
  - kind: ServiceAccount
    name: {{ include "trigger-dev.serviceAccountName" . }}
    namespace: {{ .Values.namespace | default .Release.Namespace }}
{{- end }} 