apiVersion: v2
name: trigger-dev
description: A Helm chart for Trigger.dev - an open-source platform for creating event-driven background tasks and workflows
type: application
version: 3.3.18
appVersion: "3.3.18"
icon: https://raw.githubusercontent.com/triggerdotdev/trigger.dev/main/apps/web/public/icon.png
keywords:
  - trigger.dev
  - workflow
  - automation
  - background-jobs
  - event-driven
  - kubernetes
  - jobs
  - tasks
home: https://trigger.dev
sources:
  - https://github.com/triggerdotdev/trigger.dev
  - https://github.com/hongkongkiwi/helm-trigger-dev
maintainers:
  - name: hongkongkiwi
    url: https://github.com/hongkongkiwi
kubeVersion: ">=1.19.0-0"
annotations:
  artifacthub.io/license: MIT
  artifacthub.io/prerelease: "false"
  artifacthub.io/containsSecurityUpdates: "false"
  artifacthub.io/changes: |
    - Added comprehensive validation rules
    - Enhanced security context settings
    - Improved documentation
    - Added production-ready configurations
