{{- if .Values.supervisor.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "trigger-dev.supervisor.name" . }}
  namespace: {{ .Values.namespace | default .Release.Namespace }}
  labels:
    {{- include "trigger-dev.labels" . | nindent 4 }}
    app.kubernetes.io/component: supervisor
spec:
  replicas: {{ .Values.supervisor.replicas }}
  selector:
    matchLabels:
      {{- include "trigger-dev.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: supervisor
  template:
    metadata:
      {{- with .Values.supervisor.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "trigger-dev.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: supervisor
        {{- with .Values.supervisor.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "trigger-dev.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      {{- if .Values.supervisor.initContainers }}
      initContainers:
        {{- toYaml .Values.supervisor.initContainers | nindent 8 }}
      {{- end }}
      {{- if .Values.priorityClassName }}
      priorityClassName: {{ .Values.priorityClassName }}
      {{- end }}
      {{- with .Values.topologySpreadConstraints }}
      topologySpreadConstraints:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}-supervisor
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: {{ include "trigger-dev.supervisor.image" . | quote }}
          imagePullPolicy: {{ .Values.supervisorImage.pullPolicy }}
          env:
            - name: NODE_ENV
              value: {{ .Values.supervisor.nodeEnv | quote }}
            - name: HTTP_SERVER_DISABLED
              value: "true"
            - name: SUPERVISOR_ENABLED
              value: "true"
            - name: SUPERVISOR_MODE
              value: {{ .Values.supervisor.mode | quote }}
            - name: TRIGGER_API_URL
              value: "http://{{ include "trigger-dev.app.name" . }}:{{ .Values.app.service.port }}"
            - name: KUBERNETES_FORCE_ENABLED
              value: "true"
            - name: KUBERNETES_NAMESPACE
              value: "{{ .Values.namespace | default .Release.Namespace }}"
            - name: KUBERNETES_IMAGE_PULL_POLICY
              value: "IfNotPresent"
            - name: DATABASE_CONNECTION_RETRIES
              value: "5"
            - name: DATABASE_CONNECTION_RETRY_DELAY_MS
              value: "2000"
            - name: REDIS_CONNECTION_RETRIES
              value: "5"
            - name: REDIS_CONNECTION_RETRY_DELAY_MS
              value: "2000"
            - name: HEALTH_CHECK_INTERVAL_MS
              value: "10000"
            - name: HEALTH_CHECK_TIMEOUT_MS
              value: "5000"
          {{- include "trigger-dev.commonEnv" . | nindent 12 }}
          {{- with .Values.supervisor.env }}
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.supervisor.startupProbe }}
          startupProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.supervisor.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.supervisor.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          resources:
            {{- toYaml .Values.resources.supervisor | nindent 12 }}
      {{- with .Values.supervisor.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.supervisor.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.supervisor.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}