{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "trigger-dev.fullname" . }}
  namespace: {{ .Values.namespace | default .Release.Namespace }}
  labels:
    {{- include "trigger-dev.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "trigger-dev.selectorLabels" . | nindent 6 }}
  ingress:
    - from:
        - podSelector:
            matchLabels:
              {{- include "trigger-dev.selectorLabels" . | nindent 14 }}
      ports:
        - port: http
          protocol: TCP
    {{- if .Values.networkPolicy.additionalIngress }}
    {{- toYaml .Values.networkPolicy.additionalIngress | nindent 4 }}
    {{- end }}
  egress:
    - {}
{{- end }} 