name: Helm Chart Release

on:
  push:
    branches: [ main ]
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.12.0

      - name: Cache Helm dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/helm
            ~/.config/helm
          key: ${{ runner.os }}-helm-${{ hashFiles('**/Chart.yaml', '**/Chart.lock') }}
          restore-keys: |
            ${{ runner.os }}-helm-

      - name: Package Helm Chart
        run: |
          helm package .

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: |
            *.tgz
          draft: false
          prerelease: false
          generate_release_notes: true
          fail_on_unmatched_files: true 